services:
  booking-db:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - booking-db-data:/var/lib/postgresql/data

volumes:
  booking-db-data:
    driver: local
